services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./media:/var/www/media
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db_arkiymparisto_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  db_arkiymparisto_data:
