# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 12:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nimi')),
                ('area', djgeojson.fields.GeometryField(verbose_name='area')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0, verbose_name='status')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='budget')),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'assignments',
                'verbose_name': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='OpenTextTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'open text tasks',
                'verbose_name': 'open text task',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description')),
                ('video', models.URLField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assignments.Assignment')),
            ],
            options={
                'verbose_name_plural': 'sections',
                'verbose_name': 'section',
            },
        ),
        migrations.AddField(
            model_name='opentexttask',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_text_tasks', to='assignments.Section'),
        ),
    ]
