# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='schools',
            field=models.ManyToManyField(related_name='assignments', to='assignments.School'),
        ),
    ]
