# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_budgeting_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetingTargetAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('point', djgeojson.fields.PointField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='assignments.Assignment')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assignments.School')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assignments.SchoolClass')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(related_name='schools', to='assignments.SchoolClass'),
        ),
        migrations.AddField(
            model_name='opentextanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_text_answers', to='assignments.Student'),
        ),
        migrations.AddField(
            model_name='opentextanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_text_answers', to='assignments.OpenTextTask'),
        ),
        migrations.AddField(
            model_name='budgetingtargetanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_answers', to='assignments.Student'),
        ),
        migrations.AddField(
            model_name='budgetingtargetanswer',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_answers', to='assignments.BudgetingTarget'),
        ),
        migrations.AddField(
            model_name='budgetingtargetanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeting_answers', to='assignments.BudgetingTask'),
        ),
    ]
