# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_schools_in_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetingtask',
            name='budgeting_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'map')], default=0, verbose_name='type'),
        ),
    ]
