# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_budgeting_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, default='assignment/image/default.jpg', upload_to='assignment/image/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='icon',
            field=models.ImageField(blank=True, default='target/icons/default.png', upload_to='target/icons/', verbose_name='icon'),
        ),
    ]
