# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='header',
            field=models.CharField(max_length=255, null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(help_text='The user-friendly URL identifier ex. www.example.com/runosmaen-koulu', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='icon',
            field=models.FileField(blank=True, default='target/icons/default.png', upload_to='target/icons/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='targets',
            field=models.ManyToManyField(related_name='budgeting_tasks', to='assignments.BudgetingTarget', verbose_name='budget targets'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='unit',
            field=models.IntegerField(choices=[(0, 'ha'), (1, 'pcs')], default=0, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='opentexttask',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='section',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assignments.Assignment', verbose_name='Assignment'),
        ),
    ]
