# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='schools',
            field=models.ManyToManyField(related_name='assignments', to='assignments.School', verbose_name='schools'),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(related_name='schools', to='assignments.SchoolClass', verbose_name='classes'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
