# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntarySignupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarysignuptasks', to='assignments.Section')),
            ],
            options={
                'verbose_name_plural': 'voluntary signup tasks',
                'verbose_name': 'voluntary signup task',
            },
        ),
    ]
