# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_fix_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(help_text='The user-friendly URL identifier ex. http://www.example.com/minun-runosmakeni/', max_length=80, unique=True),
        ),
    ]
