# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_target_icon_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
