# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_school_class_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
    ]
