# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 10:14
from __future__ import unicode_literals

import assignments.fields
import django_ckeditor_5.fields
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_school_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['name'], 'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='area',
            field=djgeojson.fields.GeometryField(help_text='Area name', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget allocated for the assignment', max_digits=10, verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Text used as a description of the landing section', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='header',
            field=models.CharField(help_text='Text used as a header of the landing section', max_length=255, null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image of the landing section', null=True, upload_to='assignment/image/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(help_text='Assignment name', max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='schools',
            field=models.ManyToManyField(help_text='Schools that are participating in the assignment<br>', related_name='assignments', to='assignments.School', verbose_name='schools'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0, help_text='Status of the assignment. Only opened assignments are presented to the users', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='icon',
            field=models.FileField(blank=True, help_text='Budgeting target icon. If not set, default icon is used', null=True, upload_to='target/icons/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount that can be spent on the target.<br>If set, it is used in validation of entered value', max_digits=10, null=True, verbose_name='max amount'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount that should be spent on the target.<br>Used in validation of entered value. Defaults to 0', max_digits=10, verbose_name='min amount'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='name',
            field=models.CharField(help_text='Budgeting target name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='reference_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount spent by public service that can be used as a reference value for the answer', max_digits=10, verbose_name='reference amount'),
        ),
        migrations.AlterField(
            model_name='budgetingtarget',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for a single target unit', max_digits=10, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='budgeting_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'map')], default=0, help_text='Budgeting task type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='name',
            field=models.CharField(help_text='Budgeting task name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='targets',
            field=assignments.fields.SortedAsSelectedManyToManyField(help_text='Budgeting targets related to the task<br>', related_name='budgeting_tasks', to='assignments.BudgetingTarget', verbose_name='budget targets'),
        ),
        migrations.AlterField(
            model_name='budgetingtask',
            name='unit',
            field=models.IntegerField(choices=[(0, 'ha'), (1, 'pcs')], default=0, help_text='Unit in which task amount is expressed', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='opentexttask',
            name='question',
            field=models.TextField(help_text='Question answered as a plain text', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(related_name='schools', to='assignments.SchoolClass', verbose_name='grades'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='School name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='assignment',
            field=models.ForeignKey(help_text='Assignment this section is related to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assignments.Assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Text used as a section description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text='Section title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.URLField(blank=True, help_text='YouTube URL of the video embedded in the section', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(help_text='Section this task is related to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assignments.Section'),
        ),
        migrations.AlterField(
            model_name='voluntarysignuptask',
            name='name',
            field=models.CharField(help_text='Name of the voluntary task', max_length=255, verbose_name='name'),
        ),
    ]
