# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_help_text_on_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='area',
            field=djgeojson.fields.GeometryField(help_text='Select the map area for the assignment', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(help_text='Grade name', max_length=255, verbose_name='name'),
        ),
    ]
