# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_add_missing_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetingtask',
            name='unit',
            field=models.IntegerField(choices=[(0, 'ha'), (2, 'km'), (1, 'pcs')], default=0, help_text='Unit in which task amount is expressed', verbose_name='unit'),
        ),
    ]
